return table.freeze({
    CloneDeep = require("./Shared/CloneDeep");
    IsArray = require("./Shared/IsArray");
    IsMap = require("./Shared/IsMap");
    IsMixed = require("./Shared/IsMixed");
    IsPureArray = require("./Shared/IsPureArray");
    IsPureMap = require("./Shared/IsPureMap");
    Keys = require("./Shared/Keys");
    Lockdown = require("./Shared/Lockdown");
    SetUnresizable = require("./Shared/SetUnresizable");
    SwapKeysValues = require("./Shared/SwapKeysValues");
    Values = require("./Shared/Values");
})