return table.freeze({
    FromValues = require("./FromValues");
    Difference = require("./Difference");
    Equals = require("./Equals");
    FromKeys = require("./FromKeys");
    Insert = require("./Insert");
    Intersection = require("./Intersection");
    IsProperSubset = require("./IsProperSubset");
    IsSubset = require("./IsSubset");
    Remove = require("./Remove");
    SymmetricDifference = require("./SymmetricDifference");
    ToArray = require("./ToArray");
    Union = require("./Union");
})